sudo: required
services:
  - docker
before_script:
  - docker pull centos:centos6
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build  -t javiervivanco/docker-php-centos-65 .
  - docker push javiervivanco/docker-php-centos-65